baseURL = "https://blog.liusiwei.com"
languageCode = "en-us"
title = "Siwei's Blog"

theme = "basics"

publishDir = "docs"
pygmentsStyle = "autumn"

[params]
	author = "Siwei"
	github = "yjlo123"

[permalinks]
	post = "/post/:title/"
