baseURL = "https://blog.siwei.dev"
languageCode = "en-us"
title = "Siwei's Blog"

theme = "basics"

publishDir = "docs"
pygmentsStyle = "autumn"

[params]
	author = "Siwei"
	github = "yjlo123"

[permalinks]
	post = "/post/:title/"
	leetcode = "/leetcode/:title/"

[markup]
	[markup.goldmark]
		[markup.goldmark.renderer]
			unsafe = true
